slackpkg, kvm, bind, ntp, openssl updates, and add gstreamer plugins

diff --git a/n/openssl/openssl.SlackBuild b/n/openssl/openssl.SlackBuild
--- a/n/openssl/openssl.SlackBuild
+++ b/n/openssl/openssl.SlackBuild
@@ -27,7 +27,7 @@ TMP=${TMP:-/tmp}
 
 VERSION=${VERSION:-0.9.8i}
 ARCH=${ARCH:-x86_64}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 DISTRO=${DISTRO:-slamd64}
 
 if [ $DISTRO = slackware ]; then
@@ -54,6 +54,10 @@ if [ "$ARCH" = "i486" ]; then
   # Build with -march=i486 -mtune=i686:
   zcat $CWD/openssl.optsx86.diff.gz | patch -p1 --backup --verbose --suffix=.orig || exit 1
 fi
+
+# Fix function return value error (CVE-2008-5077):
+cat $CWD/secadv_20090107.txt | patch -p1 --verbose || exit 1
+
 chown -R root:root .
 mkdir -p $PKG1/usr/doc/openssl-$VERSION
 cp -a CHANGES CHANGES.SSLeay FAQ INSTALL INSTALL.MacOS INSTALL.VMS INSTALL.W32 \
